image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

before_build:
  - .paket\paket.exe update
  - .paket\paket.exe install

build_script:
  - cmd: build.cmd

test: off

version: 0.0.1.{build}
